oli-obk/ui_test

- .vscode/settings.json
- src/lib.rs
For https://github.com/rust-lang/miri/pull/2449
> Sync with miri

- src/lib.rs
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
The 2nd commit avoids `cargo test` leaving behind some changes in git.
> some cleanup

- .github/workflows/rust.yml
- rust-toolchain.toml
and then use another approach to set the toolchain for CI
Fixes https://github.com/oli-obk/ui_test/issues/18
> remove rust-toolchain.toml

- .github/workflows/rust.yml
- tests/integration.rs
- tests/integrations/basic-fail/Cargo.stderr
> Use latest stable

- src/lib.rs
No need to do this inside `filter`.
> move code further out of a closure

- src/lib.rs
- src/parser.rs
- tests/integrations/basic-fail/Cargo.stderr
> Add a new filter scheme for host triples

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/parser.rs
- tests/integration.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.stdout
- tests/integrations/basic-fail-mode/tests/run_file.rs
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic-fail/Cargo.stderr
- tests/integrations/basic-fail/Cargo.toml
- tests/integrations/basic-fail/tests/actual_tests_bless/foomp-rustfix-fail.fixed
- tests/integrations/basic-fail/tests/actual_tests_bless/foomp-rustfix-fail.rs
- tests/integrations/basic-fail/tests/actual_tests_bless/foomp-rustfix-fail.stderr
- tests/integrations/basic-fail/tests/ui_tests_invalid_program.rs
- tests/integrations/basic-fail/tests/ui_tests_invalid_program2.rs
- tests/integrations/basic/Cargo.lock
- tests/integrations/basic/Cargo.stderr
- tests/integrations/basic/tests/actual_tests/foomp-rustfix.fixed
- tests/integrations/basic/tests/actual_tests/foomp-rustfix.rs
- tests/integrations/basic/tests/actual_tests/foomp-rustfix.stderr
- tests/integrations/basic/tests/ui_tests.rs
> Implement `//@run-rustfix`

- .gitattributes
- .github/workflows/rust.yml
- CONTRIBUTING.md
- src/diff.rs
- src/lib.rs
- tests/integration.rs
- tests/integrations/basic-bin/Cargo.stderr
- tests/integrations/basic-bin/tests/ui_tests.rs
- tests/integrations/basic-fail-mode/Cargo.stderr
- tests/integrations/basic-fail-mode/Cargo.stdout
- tests/integrations/basic-fail-mode/tests/ui_tests.rs
- tests/integrations/basic-fail/Cargo.stderr
- tests/integrations/basic-fail/tests/actual_tests/foomp.stderr
- tests/integrations/basic-fail/tests/ui_tests.rs
- tests/integrations/basic-fail/tests/ui_tests_bless.rs
- tests/integrations/basic/Cargo.stderr
- tests/integrations/basic/Cargo.stdout
- tests/integrations/basic/tests/run_file.rs
- tests/integrations/basic/tests/ui_tests.rs
work towards https://github.com/rust-lang/miri/issues/2724
> Try running tests on multiple platforms

- src/lib.rs
- src/parser.rs
- tests/integrations/basic-fail/Cargo.stderr
- tests/integrations/basic-fail/tests/actual_tests_bless/non_top_level_configs.rs
> Ensure typos or accidental nested comments don't silently do nothing

- Cargo.lock
- Cargo.toml
- src/dependencies.rs
- src/lib.rs
- src/parser.rs
- src/tests.rs
- tests/integration.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-bin/Cargo.stderr
- tests/integrations/basic-bin/tests/ui_tests.rs
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.stderr
- tests/integrations/basic-fail-mode/tests/run_file.rs
- tests/integrations/basic-fail-mode/tests/ui_tests.rs
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic-fail/Cargo.stderr
- tests/integrations/basic-fail/tests/ui_tests.rs
- tests/integrations/basic-fail/tests/ui_tests_bless.rs
- tests/integrations/basic-fail/tests/ui_tests_invalid_program.rs
- tests/integrations/basic-fail/tests/ui_tests_invalid_program2.rs
- tests/integrations/basic/Cargo.lock
- tests/integrations/basic/Cargo.stderr
- tests/integrations/basic/tests/actual_tests/subdir/aux_proc_macro.rs
- tests/integrations/basic/tests/actual_tests/unicode.rs
- tests/integrations/basic/tests/run_file.rs
- tests/integrations/basic/tests/ui_tests.rs
Changes on the clippy side are happening here: https://github.com/rust-lang/rust-clippy/pull/10426
> Changes needed by clippy

- src/github_actions.rs
- src/lib.rs
- src/parser.rs
- src/rustc_stderr.rs
- src/status_emitter.rs
- tests/integration.rs
- tests/integrations/basic-bin/Cargo.stderr
- tests/integrations/basic-bin/tests/ui_tests.rs
- tests/integrations/basic-fail-mode/Cargo.stderr
- tests/integrations/basic-fail-mode/tests/ui_tests.rs
- tests/integrations/basic-fail/Cargo.stderr
- tests/integrations/basic-fail/tests/ui_tests.rs
- tests/integrations/basic-fail/tests/ui_tests_bless.rs
- tests/integrations/basic-fail/tests/ui_tests_invalid_program.rs
- tests/integrations/basic-fail/tests/ui_tests_invalid_program2.rs
- tests/integrations/basic/Cargo.stderr
- tests/integrations/basic/tests/ui_tests.rs
allow miri to fix https://github.com/oli-obk/ui_test/issues/58 on its end.
> make gha emitting configurable

- src/status_emitter.rs
- tests/integrations/basic-fail/Cargo.stderr
> Show revisions in the failure summary

- .github/workflows/rust.yml
- CONTRIBUTING.md
- tests/integration.rs
I only ever use blessing anyway and only need checking on CI
> Default to blessing and require extra flags for checking.

- src/lib.rs
- tests/integrations/basic-fail/Cargo.stderr
> Print env vars of commands when dumping the command

- src/cmd.rs
- src/config.rs
- src/dependencies.rs
- src/error.rs
- src/lib.rs
- src/mode.rs
- src/tests.rs
- tests/integration.rs
- tests/integrations/basic-bin/tests/ui_tests.rs
- tests/integrations/basic-fail-mode/tests/run_file.rs
- tests/integrations/basic-fail-mode/tests/ui_tests.rs
- tests/integrations/basic-fail/Cargo.stderr
- tests/integrations/basic-fail/tests/ui_tests.rs
- tests/integrations/basic-fail/tests/ui_tests_bless.rs
- tests/integrations/basic-fail/tests/ui_tests_invalid_program.rs
- tests/integrations/basic-fail/tests/ui_tests_invalid_program2.rs
- tests/integrations/basic/tests/run_file.rs
- tests/integrations/basic/tests/ui_tests.rs
* removes `Default` impl as there are no sane defaults
* fixes fallout from that
> Clean up `Config`

- Cargo.lock
- Cargo.toml
- src/config.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic/Cargo.lock
miri needs this to fix https://github.com/rust-lang/miri/issues/2967
> Expose dependency building to users

- Cargo.lock
- Cargo.toml
- src/parser.rs
- src/parser/tests.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic-fail/Cargo.stderr
- tests/integrations/basic-fail/tests/actual_tests_bless/compile_flags_quotes.rs
- tests/integrations/basic/Cargo.lock
cc @boxyuwu I found a `leftpad` that does command line parsing for me 😆
> Fix parsing quoted compile-flags

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- README.md
- src/config.rs
- src/config/args.rs
- src/lib.rs
- src/parser/tests.rs
- src/status_emitter.rs
- tests/integration.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-bin/tests/ui_tests.rs
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail-mode/tests/ui_tests.rs
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic-fail/Cargo.stderr
- tests/integrations/basic-fail/tests/ui_tests.rs
- tests/integrations/basic-fail/tests/ui_tests_bless.rs
- tests/integrations/basic-fail/tests/ui_tests_invalid_program.rs
- tests/integrations/basic-fail/tests/ui_tests_invalid_program2.rs
- tests/integrations/basic/Cargo.lock
- tests/integrations/basic/tests/ui_tests.rs
Also fixes https://github.com/oli-obk/ui_test/issues/100 "by accident"
implements https://github.com/duchess-rs/duchess/pull/98#discussion_r1255476188
> Add a CLI parser that mostly matches the builtin libtest

- src/error.rs
- src/lib.rs
- src/mode.rs
- src/parser.rs
- src/parser/opt_with_line.rs
- src/parser/tests.rs
- src/status_emitter.rs
- src/tests.rs
- tests/integrations/basic-fail/Cargo.stderr
- tests/integrations/basic-fail/tests/actual_tests/bad_pattern.fixed
Plus some cleanups around "keep line information next to the actual data"
fixes #104
> Ensure we don't miss stray .fixed files

- src/error.rs
- src/github_actions.rs
- src/lib.rs
- src/mode.rs
- src/parser.rs
- src/parser/opt_with_line.rs
- src/parser/tests.rs
- src/tests.rs
> NonZero all the line numbers

- src/github_actions.rs
> Remove gha debugging helper

- src/diff.rs
fixes https://github.com/oli-obk/ui_test/issues/110
> Highlight character diffs on the background to make them more obvious

- src/config.rs
- src/dependencies.rs
- src/diff.rs
- src/lib.rs
- src/read_helper.rs
- src/status_emitter.rs
- tests/integrations/basic-bin/Cargo.stderr
- tests/integrations/basic-fail-mode/Cargo.stderr
- tests/integrations/basic-fail/Cargo.stderr
- tests/integrations/basic/Cargo.stderr
cc https://github.com/rust-lang/miri/issues/2998
> Move aux builds and dependency building into the regular status emitter

- Cargo.lock
- Cargo.toml
- src/status_emitter.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic/Cargo.lock
cc https://github.com/rust-lang/miri/pull/3008
> Some indicatif cleanups

- Cargo.lock
- Cargo.toml
- src/dependencies.rs
- src/diff.rs
- src/lib.rs
- src/status_emitter.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic/Cargo.lock
found in https://github.com/rust-lang/miri/pull/3008
> A bunch of cleanups

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/read_helper.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic/Cargo.lock
see https://github.com/rust-lang/miri/pull/3008 for some debugging around this
> Avoid a few avenues for spurious failures

- Cargo.lock
- Cargo.toml
- src/lib.rs
- tests/integration.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic/Cargo.lock
> Reintroduce path argument to per-file-config closure

- src/config.rs
- src/lib.rs
- src/parser.rs
- tests/integration.rs
> Add normalize-stdout-test filters

- README.md
> Write documentation from the test author perspective, not from the test suite author perspective

- src/lib.rs
I completely misunderstood the old comment. This should help :)
> clarify run_tests_generic doc comment

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/parser.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic-fail/Cargo.stdout
- tests/integrations/basic/Cargo.lock
- tests/integrations/cargo-run/Cargo.lock
> bump spanned dep

- CHANGELOG.md
- src/lib.rs
> Multi file suggs

- CHANGELOG.md
- src/status_emitter.rs
> Wait for printing thread to finish at shutdown

- Cargo.toml
- src/aux_builds.rs
- src/build_manager.rs
- src/cmd.rs
- src/config.rs
- src/core.rs
- src/custom_flags.rs
- src/custom_flags/run.rs
- src/custom_flags/rustfix.rs
- src/dependencies.rs
- src/filter.rs
- src/lib.rs
- src/parser.rs
- src/per_test_config.rs
- src/status_emitter.rs
- src/test_result.rs
- src/tests.rs
- tests/integrations/basic-fail/Cargo.stdout
- tests/integrations/basic/Cargo.stdout
> properly register custom flags' status emitters

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/aux_builds.rs
- src/custom_flags/run.rs
- src/custom_flags/rustfix.rs
- src/diagnostics.rs
- src/error.rs
- src/lib.rs
- src/parser.rs
- src/parser/tests.rs
- src/per_test_config.rs
- src/rustc_stderr.rs
- src/status_emitter.rs
- src/tests.rs
- tests/integration.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic-fail/Cargo.stdout
- tests/integrations/basic-fail/tests/actual_tests_bless/unicode.rs
- tests/integrations/basic-fail/tests/actual_tests_bless/unicode.stderr
- tests/integrations/basic/Cargo.lock
- tests/integrations/cargo-run/Cargo.lock
- tests/integrations/cargo-run/tests/ui_tests.rs
- tests/integrations/dep-fail/Cargo.lock
- tests/integrations/ui_test_dep_bug/Cargo.lock
> Fully switch to byte based offsets

- CHANGELOG.md
- README.md
- examples/rustc_basic.rs
- examples_tests/rustc_basic/hello.rs
- examples_tests/rustc_basic/hello.stderr
> Usage instructions and basic usage example

- .gitignore
- CHANGELOG.md
- src/config.rs
- src/parser.rs
> Comment symbols

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/config.rs
- src/parser.rs
- src/parser/tests.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic-fail/tests/actual_tests_bless/rustfix-fail-revisions.a.stderr
- tests/integrations/basic-fail/tests/actual_tests_bless/rustfix-fail-revisions.b.stderr
- tests/integrations/basic-fail/tests/actual_tests_bless/rustfix-fail.stderr
- tests/integrations/basic/Cargo.lock
- tests/integrations/basic/tests/actual_tests/aux_derive.stderr
- tests/integrations/cargo-run/Cargo.lock
- tests/integrations/dep-fail/Cargo.lock
- tests/integrations/ui_test_dep_bug/Cargo.lock
> Disjunctive filters

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/custom_flags.rs
- src/custom_flags/edition.rs
- src/per_test_config.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic/Cargo.lock
- tests/integrations/cargo-run/Cargo.lock
- tests/integrations/dep-fail/Cargo.lock
- tests/integrations/ui_test_dep_bug/Cargo.lock
> Make a bunch of things public so that miri can use them

- .github/workflows/rust.yml
- Cargo.toml
- examples/rustc_basic.rs
- src/config.rs
- src/lib.rs
- src/parser/tests.rs
- src/tests.rs
> Make everything work without the rustc feature

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/per_test_config.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic/Cargo.lock
- tests/integrations/cargo-run/Cargo.lock
- tests/integrations/dep-fail/Cargo.lock
- tests/integrations/ui_test_dep_bug/Cargo.lock
> Make more things public for miri

- Cargo.toml
- src/diagnostics.rs
> gate 2 deps under rustc feature

- tests/integrations/basic-fail/Cargo.stdout
- tests/integrations/dep-fail/Cargo.lock
- tests/integrations/dep-fail/Cargo.stdout
- tests/integrations/ui_test_dep_bug/Cargo.lock
1.82 has slightly different output.
> Bless test output for 1.82

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- rust-toolchain.toml
- src/lib.rs
- tests/integrations/basic-fail/Cargo.stdout
- tests/integrations/basic-fail/tests/actual_tests_bless/rustfix-fail-revisions.a.stderr
- tests/integrations/basic-fail/tests/actual_tests_bless/rustfix-fail-revisions.b.stderr
- tests/integrations/basic-fail/tests/actual_tests_bless/rustfix-fail.stderr
- tests/integrations/basic/tests/actual_tests/aux_derive.stderr
- tests/integrations/dep-fail/Cargo.stdout
> Always run tests on MSRV

- examples/rustc_basic.rs
- examples/rustc_twice_with_different_flags.rs
- src/aux_builds.rs
- src/build_manager.rs
- src/config.rs
- src/core.rs
- src/custom_flags/run.rs
- src/custom_flags/rustfix.rs
- src/dependencies.rs
- src/lib.rs
- src/per_test_config.rs
- src/test_result.rs
- tests/integrations/basic-fail/Cargo.stdout
> Make `Errored` debug rendering readable

- README.md
I'm working on enforcing annotation in clippy ui tests and understanding revisions took me more time than I think it should have. I think adding a code example will be helpful for potential users or future me.
> Add example for revisions

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/config.rs
- src/error.rs
- src/per_test_config.rs
- src/status_emitter/gha.rs
- src/status_emitter/text.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic-fail/Cargo.stdout
- tests/integrations/basic/Cargo.lock
- tests/integrations/cargo-run/Cargo.lock
- tests/integrations/dep-fail/Cargo.lock
- tests/integrations/ui_test_dep_bug/Cargo.lock
> Show the unnormalized output on output mismatch failure

- Cargo.lock
- Cargo.toml
So you can click on the release button on your phone. :wink:
> Update crate version to `0.29.2`

- src/status_emitter/gha.rs
Fixes https://github.com/oli-obk/ui_test/issues/323.
> Fix GHA emitter line count panic

- .github/workflows/rust.yml
- Cargo.lock
Fixes https://github.com/oli-obk/ui_test/issues/330
> CI: ensure a build with --locked succeeds
