oli-obk/ui_test

- Cargo.lock
- Cargo.toml
- src/diff.rs
- src/lib.rs
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic-fail/Cargo.stderr
- tests/integrations/basic/Cargo.lock
Rebase, fixup and different repo for https://github.com/rust-lang/miri/pull/2400
> Create a more compact diff format

- Cargo.toml
If you don't like the documentation tag, because it leads to the rust repo and maybe divert from your code or is not applicable, I can remove that :)
> add repository and documentation tag to Cargo.toml

- Cargo.lock
- Cargo.toml
- src/lib.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic/Cargo.lock
Removed crossbeam, replaced with `thread::scope` and `crossbeam_channel`.
> replaced crossbeam with scoped threads

- src/lib.rs
The inner functions no expect target/host to be `Some`; `run_tests_generic` sets appropriate values if they start out as `None`.
Fixes https://github.com/oli-obk/ui_test/issues/15
> fix on-host condition for the case where the target is explicitly set to be the host

- .github/workflows/rust.yml
using https://github.com/obi1kenobi/cargo-semver-check to automatically fail CI if a change is done without the appropriate `Cargo.toml` version bump
> Add semver checks to CI

- README.md
- src/lib.rs
- src/parser.rs
- src/parser/tests.rs
- tests/integration.rs
- tests/integrations/basic-fail/Cargo.stderr
- tests/integrations/basic-fail/Cargo.stdout
- tests/integrations/basic-fail/Cargo.toml
- tests/integrations/basic-fail/tests/actual_tests_bless/revised_revision.rs
- tests/integrations/basic-fail/tests/actual_tests_bless/revisions.bar.stderr
- tests/integrations/basic-fail/tests/actual_tests_bless/revisions.foo.stderr
- tests/integrations/basic-fail/tests/actual_tests_bless/revisions.rs
- tests/integrations/basic-fail/tests/actual_tests_bless/revisions_bad.bar.stderr
- tests/integrations/basic-fail/tests/actual_tests_bless/revisions_bad.foo.stderr
- tests/integrations/basic-fail/tests/actual_tests_bless/revisions_bad.rs
- tests/integrations/basic-fail/tests/actual_tests_bless/revisions_filter.rs
- tests/integrations/basic-fail/tests/actual_tests_bless/revisions_filter2.bar.stderr
- tests/integrations/basic-fail/tests/actual_tests_bless/revisions_filter2.rs
- tests/integrations/basic-fail/tests/actual_tests_bless/revisions_multiple_per_annotation.bar.stderr
- tests/integrations/basic-fail/tests/actual_tests_bless/revisions_multiple_per_annotation.foo.stderr
- tests/integrations/basic-fail/tests/actual_tests_bless/revisions_multiple_per_annotation.rs
- tests/integrations/basic-fail/tests/actual_tests_bless/revisions_same_everywhere.bar.stderr
- tests/integrations/basic-fail/tests/actual_tests_bless/revisions_same_everywhere.foo.stderr
- tests/integrations/basic-fail/tests/actual_tests_bless/revisions_same_everywhere.rs
- tests/integrations/basic-fail/tests/ui_tests_bless.rs
> Revise revisions

- src/lib.rs
`cargo test` is not quiet per default, let's match that.
> make quite not the default

- src/github_actions.rs
- src/lib.rs
- tests/integration.rs
> GitHub actions diagnostics

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/parser.rs
- tests/integration.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic/Cargo.lock
Using Mode for `run-pass` made me realize that `run-rustfix` is also just a mode
> Make run-rustfix a full Mode

- Cargo.lock
- Cargo.toml
- src/lib.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail-mode/tests/run_file.rs
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic-fail/Cargo.stderr
- tests/integrations/basic/Cargo.lock
- tests/integrations/basic/tests/run_file.rs
This allows callers to choose how they get their output
> Provide a command for running a single test instead of running it directly

- src/dependencies.rs
- src/lib.rs
- src/status_emitter.rs
- tests/integration.rs
- tests/integrations/basic-bin/tests/ui_tests.rs
- tests/integrations/basic-fail-mode/tests/ui_tests.rs
- tests/integrations/basic-fail/Cargo.stderr
- tests/integrations/basic-fail/tests/ui_tests.rs
- tests/integrations/basic-fail/tests/ui_tests_bless.rs
- tests/integrations/basic-fail/tests/ui_tests_invalid_program.rs
- tests/integrations/basic-fail/tests/ui_tests_invalid_program2.rs
- tests/integrations/basic/tests/ui_tests.rs
The command differs from user to user. E.g. miri uses `./miri bless`, while most other users use `cargo test -- -- --bless` or `env BLESS=1 cargo test`
> Show the command that should be run to fix any test failures

- src/config.rs
See https://github.com/rust-lang/rust/pull/113151 for a situation where this was a problem
> Prefer the `CARGO_TARGET_DIR` env var over the local directory.

- src/parser.rs
- tests/integrations/basic-fail/Cargo.stderr
- tests/integrations/basic-fail/tests/actual_tests/pattern_too_many_arrow.rs
A `-` without checks meant that determining what line a `//~^` was pointing to could overflow. Emit an error since that's never a well formed comment.
> error when an error pattern comment refers to a line that doesn't exist

- src/dependencies.rs
see https://github.com/rust-lang/rust/issues/113585
> Guard against crate id collisions

- .github/workflows/rust.yml
- Cargo.toml
- src/config.rs
- src/lib.rs
- tests/integrations/basic/Cargo.stderr
- tests/integrations/basic/tests/actual_tests/windows_paths.rs
- tests/integrations/basic/tests/actual_tests/windows_paths.stderr
Fixes #89
Slightly different than [the rustc one](https://github.com/rust-lang/rust/blob/6ce22733b973355573efd1e6294e585460e90e17/src/tools/compiletest/src/runtest.rs#L3748-L3775), it assumes it will be ran against generally unsubstituted paths (no `$DIR\foo\...`) because `Config::path_stderr_filter` switches the `\`s in windows paths to `/`
It does require an extra feature enabled on `regex` for the unicode property escapes
> Add a matcher for windows path backslashes

- Cargo.lock
- Cargo.toml
- src/status_emitter.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic/Cargo.lock
This should avoid any weird interleaving and left over fragments
> Use a central thread that synchronizes all the progress bar logic.

- README.md
- src/lib.rs
- src/parser.rs
- tests/integrations/basic-fail/Cargo.stderr
- tests/integrations/basic-fail/tests/actual_tests_bless/aux_proc_macro_misuse.rs
- tests/integrations/basic-fail/tests/actual_tests_bless/aux_proc_macro_no_main.rs
- tests/integrations/basic/tests/actual_tests/aux_derive.fixed
- tests/integrations/basic/tests/actual_tests/aux_derive.rs
- tests/integrations/basic/tests/actual_tests/aux_proc_macro.rs
- tests/integrations/basic/tests/actual_tests/subdir/aux_proc_macro.rs
now that we have auto-detection for tests being binaries, tests, libraries or proc macros, use that logic for aux builds, too.
> Automatically detect aux builds that are proc macros

- src/lib.rs
- src/read_helper.rs
- src/status_emitter.rs
This is mainly useful for the dogfood test in this repo, but I assume other test suites will have long running tests, too.
Locally this allows me to see which test is currently running, and it at least provides some sort of progress information by changing what is displayed.
> Show the status of long running tests by adding their last output line to the spinner.

- src/lib.rs
- src/read_helper.rs
Don't wait on stdout, it will block until output happens, and then we don't see any stderr.
I mis-followed a clippy lint in https://github.com/oli-obk/ui_test/pull/119 and thus only showed the lines that were empty instead of the lines that had content
> Actually make the status work.

- src/config.rs
- src/dependencies.rs
- src/diff.rs
- src/lib.rs
- src/mode.rs
- src/status_emitter.rs
- tests/integration.rs
- tests/integrations/basic-bin/Cargo.stderr
- tests/integrations/basic-fail-mode/Cargo.stderr
- tests/integrations/basic-fail-mode/tests/run_file.rs
- tests/integrations/basic-fail-mode/tests/ui_tests.rs
- tests/integrations/basic-fail/Cargo.stderr
- tests/integrations/basic-fail/tests/ui_tests_bless.rs
- tests/integrations/basic/Cargo.stderr
- tests/integrations/basic/tests/run_file.rs
To get there I also only build dependencies if there is a test that wasn't filtered out by doing that during test running.
After this we should be able to refactor our test runner to run on multiple different root directories with multiple different `Config`s, instead of running each `Config` sequentially, and only having parallelism within it.
> Build aux builds only once

- Cargo.lock
- Cargo.toml
- src/config/args.rs
- src/lib.rs
- tests/integration.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-bin/tests/ui_tests.rs
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail-mode/tests/ui_tests.rs
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic-fail/tests/ui_tests.rs
- tests/integrations/basic-fail/tests/ui_tests_bless.rs
- tests/integrations/basic-fail/tests/ui_tests_invalid_program.rs
- tests/integrations/basic-fail/tests/ui_tests_invalid_program2.rs
- tests/integrations/basic/Cargo.lock
- tests/integrations/basic/tests/ui_tests.rs
cc https://github.com/rust-lang/miri/pull/3008
our command line argument requirements are simple enough for us to just parse them manually
> Remove `clap` dependency

- src/lib.rs
- src/status_emitter.rs
- tests/integration.rs
- tests/integrations/basic-bin/Cargo.stderr
- tests/integrations/basic-fail-mode/Cargo.stderr
- tests/integrations/basic-fail/Cargo.stderr
- tests/integrations/basic/Cargo.stderr
cc https://github.com/rust-lang/miri/pull/3008
> Make output more like libtest

- Cargo.lock
- Cargo.toml
- src/config/args.rs
- src/lib.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic/Cargo.lock
needed for https://github.com/rust-lang/rust-clippy/pull/11239
> Allow skipping tests via --skip

- src/config.rs
- src/lib.rs
- src/mode.rs
- src/parser.rs
- src/status_emitter.rs
- tests/integrations/basic-fail-mode/tests/ui_tests.rs
- tests/integrations/basic-fail/tests/ui_tests_bless.rs
Since https://github.com/rust-lang/rust-clippy/pull/11249 was merged we'll be wanting to move clippy from `Yolo` to `Fail` to make the annotations required, but we still want to apply non machine applicable suggestions so this adds an enum to configure rustfix
cc @GuillaumeGomez since https://github.com/rust-lang/rust-clippy/pull/11249#issuecomment-1688502203 will be blocked on this
> Allow configuring `rustfix::Filter` independently of the mode

- Cargo.lock
- Cargo.toml
- src/cmd.rs
- src/config.rs
- src/config/args.rs
- src/dependencies.rs
- src/error.rs
- src/lib.rs
- src/status_emitter.rs
- tests/integration.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-bin/tests/ui_tests.rs
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail-mode/tests/ui_tests.rs
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic-fail/Cargo.stderr
- tests/integrations/basic-fail/Cargo.stdout
- tests/integrations/basic-fail/tests/ui_tests.rs
- tests/integrations/basic-fail/tests/ui_tests_bless.rs
- tests/integrations/basic-fail/tests/ui_tests_invalid_program.rs
- tests/integrations/basic-fail/tests/ui_tests_invalid_program2.rs
- tests/integrations/basic/Cargo.lock
- tests/integrations/basic/tests/ui_tests.rs
`Args` now solely parses arguments and is used to fill in fields on `Config`, the default number of test threads is also moved into `run_tests_generic`
This reintroduces `OutputConflictHandling` as the command string in the error variant is nice to have
> Populate `Config` with `Args` instead of passing it to `run_tests_generic`

- src/lib.rs
- tests/integration.rs
- tests/integrations/basic-fail/Cargo.stderr
- tests/integrations/basic-fail/Cargo.stdout
- tests/integrations/basic-fail/tests/actual_tests/rustc_ice.rs
- tests/integrations/basic-fail/tests/actual_tests/rustc_ice.stderr
see https://github.com/rust-lang/miri/issues/3052 for the original issue
> properly handle compiler ICEs

- tests/integration.rs
- tests/integrations/basic-fail/tests/actual_tests/rustc_ice.rs
Fixes https://github.com/oli-obk/ui_test/issues/168
> fix 'cargo test'

- src/error.rs
- src/lib.rs
- src/status_emitter.rs
- src/tests.rs
- tests/integrations/basic-fail/Cargo.stdout
In particular the current text is confusing if the substring *does* appear in stderr, but not on the right line.
> be more specific about what the pattern expects

- src/status_emitter.rs
- tests/integrations/basic-fail/Cargo.stdout
In large errors I feel it is easy to miss when somewhere at the top it also says "got exit status: 0, but expected 1", or so.
Ideally all errors would do this consistently, e.g. start with a underlined title and then perhaps have more details. However that doesn't really work for the errors that show a span... but maybe ut's worth doing that at least for these two otherwise-easy-to-miss errors?
> make individual errors in a failed test more clearly visible

- Cargo.lock
- Cargo.toml
- src/error.rs
- src/lib.rs
- src/mode.rs
- src/parser.rs
- src/parser/spanned.rs
- src/parser/tests.rs
- src/rustc_stderr.rs
- src/status_emitter.rs
- src/tests.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic/Cargo.lock
- tests/integrations/cargo-run/Cargo.lock
It now lives at https://crates.io/crates/spanned
> Move most of our span handling out into a crate

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/config.rs
- src/dependencies.rs
- src/error.rs
- src/lib.rs
- src/mode.rs
- src/parser.rs
- src/parser/spanned.rs
- src/parser/tests.rs
- src/per_test_config.rs
- src/rustc_stderr.rs
- src/status_emitter.rs
- src/tests.rs
- tests/integration.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail-mode/tests/ui_tests.rs
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic-fail/tests/ui_tests_bless.rs
- tests/integrations/basic/Cargo.lock
- tests/integrations/basic/tests/run_file.rs
- tests/integrations/cargo-run/Cargo.lock
- tests/integrations/cargo-run/tests/ui_tests.rs
implements https://github.com/oli-obk/ui_test/pull/182#issuecomment-1796525419
> Default test settings

- src/config.rs
- src/dependencies.rs
- src/error.rs
- src/lib.rs
- src/status_emitter.rs
- tests/integration.rs
- tests/integrations/basic-bin/tests/ui_tests.rs
- tests/integrations/basic-fail-mode/tests/ui_tests.rs
- tests/integrations/basic-fail/Cargo.stderr
- tests/integrations/basic-fail/tests/ui_tests.rs
- tests/integrations/basic-fail/tests/ui_tests_bless.rs
- tests/integrations/basic-fail/tests/ui_tests_invalid_program.rs
- tests/integrations/basic-fail/tests/ui_tests_invalid_program2.rs
- tests/integrations/basic/tests/ui_tests.rs
- tests/integrations/cargo-run/tests/ui_tests.rs
The usage in clippy showed that #157 made the API a bit awkward with regards to the bless command and conflict handling modes, this takes it from
```rust
let mut config = Config {
..
};
config.with_args(&args, /* bless by default */ false);
if let OutputConflictHandling::Error(err) = &mut config.output_conflict_handling {
*err = "cargo uibless".into();
}
```
to
```rust
let mut config = Config {
output_conflict_handling: OutputConflictHandling::Error,
bless_command: Some("cargo uibless".into()),
..
};
config.with_args(&args)
```
The default conflict handling is now only specified in the `Config`, no more `bool` in `with_args`
It's a separate (optional) field because in order for `OutputConflictHandling::Bless` +  `--check` to work it had to supply a bless command of its own, but there's …
> Move the bless command to a field in Config

- README.md
- src/status_emitter.rs
> Update README with ignore-host-XXX annotation

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic/Cargo.lock
- tests/integrations/cargo-run/Cargo.lock
This updates `cargo_metadata` to `0.18` in support of removing rustc duplicates here: https://github.com/rust-lang/rust/pull/120177
I know this was the second pull request of the day so no hurry; just trying to get a start somewhere with Rust contributions.
> Update to cargo_metadata 0.18

- CHANGELOG.md
- src/cmd.rs
- src/config.rs
- src/dependencies.rs
> Base cfg printing off the program instead of allowing separate executables

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/status_emitter.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic/Cargo.lock
- tests/integrations/cargo-run/Cargo.lock
> bump annotate-snippets to 0.10

- CHANGELOG.md
- src/lib.rs
- src/status_emitter.rs
- tests/integration.rs
> Fix filtered test reporting

- CHANGELOG.md
- src/parser.rs
- tests/integrations/basic-fail/Cargo.stdout
- tests/integrations/basic-fail/tests/actual_tests/pattern_too_many_arrow_above.rs
- tests/integrations/basic/Cargo.stdout
- tests/integrations/basic/tests/actual_tests/error_above.rs
- tests/integrations/basic/tests/actual_tests/error_above.stderr
Clippy has some lints which take comments into account and where the error span encompasses multiple lines. Currently this requires putting the matcher many lines later and then counting the lines. e.g.
```rust
if foo {
foo;
bar;
baz;
} else {
foo;
bar;
baz;
} 
//~^^^^^^^^^ ERROR: same if else bodies
```
This patch allows putting the matcher above, avoiding the problem.
```rust
//~v ERROR: same if else bodies
if foo {
foo;
bar;
baz;
} else {
foo;
bar;
baz;
} 
```
> Allow error comments above the error site.

- src/lib.rs
Aux builds use the wrong settings otherwise. (e.g. building for the 2015 edition)
> Use default comments when building auxiliary files

- src/parser.rs
- tests/integrations/basic-fail/Cargo.stdout
- tests/integrations/basic-fail/tests/actual_tests/inline_chain.rs
- tests/integrations/basic-fail/tests/actual_tests/joined_wrong_order.rs
- tests/integrations/basic-fail/tests/actual_tests/lone_joined_pattern.rs
- tests/integrations/basic-fail/tests/actual_tests/touching_above_below.rs
- tests/integrations/basic-fail/tests/actual_tests/touching_above_below_chain.rs
- tests/integrations/basic/Cargo.stdout
- tests/integrations/basic/tests/actual_tests/joined_above.fixed
- tests/integrations/basic/tests/actual_tests/joined_above.rs
- tests/integrations/basic/tests/actual_tests/joined_above.stderr
- tests/integrations/basic/tests/actual_tests/joined_below.fixed
- tests/integrations/basic/tests/actual_tests/joined_below.rs
- tests/integrations/basic/tests/actual_tests/joined_below.stderr
- tests/integrations/basic/tests/actual_tests/joined_mixed.fixed
- tests/integrations/basic/tests/actual_tests/joined_mixed.rs
- tests/integrations/basic/tests/actual_tests/joined_mixed.stderr
Fixes an oversight from when `//~v` comments were added. Current implementation flips the order required which wouldn't be backwards compatible. Supporting stacking both above and below would be trivial if you'd prefer.
This should probably error when it's ambiguous which arrow to follow, though it currently binds above in such a case. e.g.
```rust
//~^ error
//~| error2 
//~v error3
```
> Allow `//~|` comments to preceed `//~v` comments.

- src/rustc_stderr.rs
- tests/integrations/basic/Cargo.stdout
- tests/integrations/basic/tests/actual_tests/mac_span.fixed
- tests/integrations/basic/tests/actual_tests/mac_span.rs
- tests/integrations/basic/tests/actual_tests/mac_span.stderr
Came up while converting clippy to use annotations.
> Don't let non-primary spans take priority over primary spans.

- src/dependencies.rs
- src/rustc_stderr.rs
- tests/integration.rs
- tests/integrations/basic-bin/tests/actual_tests/foomp.rs
- tests/integrations/basic-bin/tests/actual_tests/foomp.stderr
- tests/integrations/basic-fail/Cargo.stdout
- tests/integrations/basic/Cargo.lock
- tests/integrations/basic/Cargo.stdout
- tests/integrations/basic/Cargo.toml
- tests/integrations/basic/tests/actual_tests/dep_derive.rs
- tests/integrations/basic/tests/actual_tests/dep_derive.stderr
Fixes https://github.com/oli-obk/ui_test/issues/203
> Support proc macro test dependencies

- README.md
`ignore-target-*` and `only-target-*` does not, in fact, "operate solely on the triple, instead of supporting things like `macos`". It actually supports things like `macos` AFAICT because ui_test seems to match the `*` as a substring of target triples.
> Fix docs for `{ignore,only}-target-*` directive differences with compiletest

- CHANGELOG.md
- src/aux_builds.rs
- src/build_manager.rs
- src/config.rs
- src/core.rs
- src/custom_flags.rs
- src/custom_flags/run.rs
- src/custom_flags/rustfix.rs
- src/dependencies.rs
- src/lib.rs
- src/mode.rs
- src/parser.rs
- src/per_test_config.rs
- src/status_emitter.rs
- src/tests.rs
- tests/integrations/basic-fail/Cargo.stdout
- tests/integrations/basic-fail/tests/ui_tests_bless.rs
The fact that this works makes me think that https://github.com/oli-obk/ui_test/issues/186 can now be implemented, even outside of this crate
> separate run and rustfix modes into their own modules

- .github/workflows/rust.yml
- CHANGELOG.md
- Cargo.toml
- src/aux_builds.rs
- src/config.rs
- src/custom_flags.rs
- src/custom_flags/run.rs
- src/custom_flags/rustfix.rs
- src/dependencies.rs
- src/diagnostics.rs
- src/error.rs
- src/lib.rs
- src/parser.rs
- src/per_test_config.rs
- src/rustc_stderr.rs
- src/status_emitter.rs
- src/tests.rs
- tests/integrations/basic-bin/tests/ui_tests.rs
- tests/integrations/basic-fail-mode/tests/run_file.rs
- tests/integrations/basic-fail-mode/tests/ui_tests.rs
- tests/integrations/basic-fail/Cargo.stderr
- tests/integrations/basic-fail/Cargo.stdout
- tests/integrations/basic-fail/tests/ui_tests.rs
- tests/integrations/basic-fail/tests/ui_tests_bless.rs
- tests/integrations/basic/tests/run_file.rs
- tests/integrations/basic/tests/ui_tests.rs
- tests/integrations/cargo-run/Cargo.stdout
Should unlock implementing https://github.com/oli-obk/ui_test/issues/105 now
> Allow overriding the test output parser

- src/tests.rs
- tests/integration.rs
This removes some redundant imports that newer versions of rustc complain about.
> Fix redundant imports

- CHANGELOG.md
- src/dependencies.rs
> Link folders and libs mentioned by build scripts

- src/custom_flags/run.rs
- src/custom_flags/rustfix.rs
- src/error.rs
- src/mode.rs
- src/status_emitter.rs
- tests/integrations/basic-fail/Cargo.stdout
fixes #219
cc https://github.com/oli-obk/ui_test/issues/105 (should be easier to implement now)
> Rustfix messaging

- tests/integration.rs
- tests/integrations/basic-fail/Cargo.stdout
- tests/integrations/basic-fail/tests/actual_tests_bless/abort.rs
> Add an abort test

- src/rustc_stderr.rs
> Don't ICE on dummy spans (rustc uses `0` for dummy values, we use usize::MAX)

- .github/workflows/rust.yml
- CHANGELOG.md
- Cargo.toml
- src/dependencies.rs
- tests/build_std.rs
As discussed in https://github.com/oli-obk/ui_test/issues/197#issuecomment-2124794280.
Fixes #197.
> Support `-Zbuild-std`

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic-fail/Cargo.stdout
- tests/integrations/basic/Cargo.lock
- tests/integrations/cargo-run/Cargo.lock
- tests/integrations/dep-fail/Cargo.lock
- tests/integrations/ui_test_dep_bug/Cargo.lock
Bumps `prettydiff` to drop `ansi_term` and `winapi`.
> bump prettydiff

- Cargo.lock
- Cargo.toml
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic/Cargo.lock
- tests/integrations/cargo-run/Cargo.lock
- tests/integrations/dep-fail/Cargo.lock
- tests/integrations/ui_test_dep_bug/Cargo.lock
Drop unused `tempfile`. Was added in #23, but unused (except tests).
> drop unused tempfile

- CHANGELOG.md
- src/custom_flags.rs
- src/custom_flags/run.rs
- src/custom_flags/rustfix.rs
- src/per_test_config.rs
- src/status_emitter.rs
- tests/integrations/basic-fail/Cargo.stdout
- tests/integrations/basic-fail/tests/actual_tests_bless_yolo/rustfix-multiple-fail.1.fixed
- tests/integrations/basic-fail/tests/actual_tests_bless_yolo/rustfix-multiple-fail.2.fixed
- tests/integrations/basic-fail/tests/actual_tests_bless_yolo/rustfix-multiple-fail.3.fixed
- tests/integrations/basic-fail/tests/actual_tests_bless_yolo/rustfix-multiple-fail.rs
- tests/integrations/basic-fail/tests/actual_tests_bless_yolo/rustfix-multiple-fail.stderr
- tests/integrations/basic-fail/tests/ui_tests_bless.rs
- tests/integrations/basic/Cargo.stdout
- tests/integrations/basic/tests/actual_tests/rustfix-multiple.1.fixed
- tests/integrations/basic/tests/actual_tests/rustfix-multiple.2.fixed
- tests/integrations/basic/tests/actual_tests/rustfix-multiple.rs
- tests/integrations/basic/tests/actual_tests/rustfix-multiple.stderr
Some clippy tests disable rustfix because they produce multiple alternative suggestions e.g. [`join_absolute_paths`](https://github.com/rust-lang/rust-clippy/blob/29cc5c691c574b54b2fcfed51c22f8bb51110919/tests/ui/join_absolute_paths.stderr). This PR allows there to be a `.fixed` file per alternative suggestion, in that example `join_absolute_paths.1.fixed` and `join_absolute_paths.2.fixed`
There are some lints that produce multiple suggestions that are intended to be combined e.g.
```
error: this binding can be a slice pattern to avoid indexing
--> tests/ui/index_refutable_slice/if_let_slice_binding.rs:21:17
|
LL |     if let Some(slice) = slice {
|                 ^^^^^
|
help: try using a slice pattern here
|
LL |     if let Some([slice_0, ..]) = slice {
|                 ~~~~~~~~~~~~~ …
```
> Create multiple `.fixed` files for diagnostics with multiple suggestions

- src/core.rs
- tests/integrations/basic/Cargo.stdout
- tests/integrations/basic/tests/actual_tests/aux_attr_proc_macro.rs
- tests/integrations/basic/tests/actual_tests/auxiliary/proc_macro_attr.rs
Our proc macro crate is called `proc_macros` so a few of our tests get compiled with `--crate=proc-macro`, didn't matter for many of them but it does for https://github.com/rust-lang/rust-clippy/blob/3b64ca95a931b0cca63e21de55b24a5bcfd4fb84/tests/ui/implicit_hasher.stderr
> Fix `#[proc_macros::...]` being detected as a proc macro crate

- src/status_emitter.rs
- tests/integration.rs
- tests/integrations/basic-bin/Cargo.stdout
- tests/integrations/basic-fail-mode/Cargo.stdout
- tests/integrations/basic-fail/Cargo.stdout
- tests/integrations/basic/Cargo.stdout
- tests/integrations/cargo-run/Cargo.stdout
- tests/integrations/dep-fail/Cargo.stdout
- tests/integrations/ui_test_dep_bug/Cargo.stdout
> Avoid extraneous semicolons

- src/lib.rs
Currently we need to go to the repository to have access to all the syntax information. Instead, this PR includes it directly into the crate documentation (but only when rustdoc is building).
> Add full readme to crate documentation

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- examples/rustc_basic.rs
- src/aux_builds.rs
- src/build_manager.rs
- src/config.rs
- src/custom_flags/run.rs
- src/custom_flags/rustfix.rs
- src/lib.rs
- src/per_test_config.rs
- src/status_emitter.rs
- src/test_result.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic/Cargo.lock
- tests/integrations/cargo-run/Cargo.lock
- tests/integrations/dep-fail/Cargo.lock
- tests/integrations/ui_test_dep_bug/Cargo.lock
fixed #166
Under some rare racy conditions sub-processes (like run tests) do not get cancelled. I think this is if Ctrl+C is pressed while the process is being started. If the subprocess is already running, it will get cancelled immediately. Probably unavoidable, but also not too common or problematic.
> Stop tests early when Ctrl+C is pressed

- src/core.rs
- src/custom_flags/rustfix.rs
- src/lib.rs
- src/parser.rs
- src/status_emitter.rs
- tests/integrations/basic-fail/Cargo.stdout
- tests/integrations/basic/Cargo.stdout
- tests/integrations/basic/tests/actual_tests/foomp.rs
- tests/integrations/basic/tests/actual_tests/foomp.stderr
> Run on clippy and make everything work again

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/parser.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic-fail/Cargo.stdout
- tests/integrations/basic-fail/tests/actual_tests_bless/normalization_override.rs
- tests/integrations/basic-fail/tests/actual_tests_bless/normalization_override.stderr
- tests/integrations/basic-fail/tests/ui_tests_bless.rs
- tests/integrations/basic/Cargo.lock
- tests/integrations/cargo-run/Cargo.lock
- tests/integrations/dep-fail/Cargo.lock
- tests/integrations/ui_test_dep_bug/Cargo.lock
fixes some normalization issues in https://github.com/rust-lang/miri/pull/3866
> run global filters before file local filters

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/filter.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic/Cargo.lock
- tests/integrations/cargo-run/Cargo.lock
- tests/integrations/dep-fail/Cargo.lock
- tests/integrations/ui_test_dep_bug/Cargo.lock
[OnceLock](https://doc.rust-lang.org/stable/std/sync/struct.OnceLock.html) stable from 1.70, which is current msrv, so use it instead (`lazy_static` still in tree),
> replace lazy_static with std's OnceLock

- CHANGELOG.md
The text previously made it sound like `//@only-64bit` and `//@only-bitwidth: 64 16` are doing the same thing. I doubt that is the case.
> Clarify changelog regarding only-bitwidth

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/build_manager.rs
- src/config.rs
- src/parser.rs
- src/parser/tests.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic/Cargo.lock
- tests/integrations/cargo-run/Cargo.lock
- tests/integrations/dep-fail/Cargo.lock
- tests/integrations/ui_test_dep_bug/Cargo.lock
> Some changes needed for miri

- Cargo.lock
- Cargo.toml
- src/status_emitter/text.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic/Cargo.lock
- tests/integrations/cargo-run/Cargo.lock
This caused multiple invocations of `run_tests` to have the latter ones just not remove their entries from the command line anymore
> Remove global variable

- CHANGELOG.md
- src/config.rs
- src/diff.rs
- src/lib.rs
- src/parser.rs
- src/parser/spanned.rs
- src/status_emitter/text.rs
`CommentParser` is unnameable from outside this crate, meaning a user cannot declare a parser function with `fn`, only inline with a closure. I've fixed this by exporting `parser::*`, and enabled the `unreachable_pub` and `unnameable_types` to catch this and other unreachable types.
> Export parser types

- src/rustc_stderr.rs
A regex in `rustc_stderr` gets created on every JSON stderr line, which shows up in profiles when running thousands of tests.  
Cache it with `OnceLock` (MSRV 1.70, also used elsewhere in the codebase).
> Cache an error parser regex

- src/config.rs
- src/diagnostics.rs
- src/diagnostics/rustc.rs
- src/lib.rs
- src/per_test_config.rs
The config `diagnostic_extractor`s provided by the `rustc` feature are not exported but reachable through `Config::{cargo,rustc}().diagnostic_extractor`; making these public would let users import the function directly instead of having it to access it through `Config` methods.
I've renamed them and moved them to the `diagnostics` module, as well as added the default one as a separate function.
My use case for this is I am testing another compiler that can emit JSON diagnostics using the rustc format, but everything else about the configuration will be different, so it doesn't really make sense to call `Config::rustc` if it wasn't for this method.
BTW I was able to migrate to this library from a compiletest-rs fork pretty easily, thanks a lot for developing this!
> Export default diagnostics extractors

- CHANGELOG.md
- src/config.rs
- src/custom_flags.rs
- src/custom_flags/revision_args.rs
- src/per_test_config.rs
- tests/integrations/basic-fail/Cargo.stdout
Closes https://github.com/oli-obk/ui_test/issues/290 by implementing the second suggestion in https://github.com/oli-obk/ui_test/issues/290#issuecomment-2447877332.
Should already be tested by existing revisions tests.
> Move revision-specific args to a custom flag

- README.md
It seems this was not updated when the syntax was changed from `ignore-target-xxx` to `ignore-target: xxx`.
> README: update ignore-target/only-target comparison with compiletest

- README.md
- src/diagnostics.rs
- tests/integrations/basic-fail/Cargo.stdout
- tests/integrations/basic-fail/tests/actual_tests/ice_annotations.rs
Needed to finish to make ui test annotations mandatory in clippy.
> Add `ICE` level parsing

- examples_tests/rustc_basic/aux_derive.stderr
Right now the examples fail; this fixes the examples.
> Correcting incorrect example

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/dependencies.rs
- tests/integrations/basic-bin/Cargo.lock
- tests/integrations/basic-fail-mode/Cargo.lock
- tests/integrations/basic-fail/Cargo.lock
- tests/integrations/basic/Cargo.lock
- tests/integrations/basic/Cargo.toml
- tests/integrations/cargo-run/Cargo.lock
- tests/integrations/dep-fail/Cargo.lock
- tests/integrations/ui_test_dep_bug/Cargo.lock
Fixes https://github.com/oli-obk/ui_test/issues/327 by looking at the path in which artifacts are stored: if we pass `--target` to cargo, that will be different for host and target crates. If a non-proc-macro host crate shows up, we just ignore it during artifact gathering.
I have confirmed that in the context of https://github.com/rust-lang/rust-clippy/pull/14883 this makes the dependency build work.
> dependencies: heuristic to distinguish host and target artifacts

- README.md
Small nits on the readme documentation. Unsure if this requires a changelog entry given the size and nature of the change.
> readme: doc comments
